baseURL = "https://hackerfarm.in/"
languageCode = "en-us"
title = "HackerFarm India"
theme = "bulma"
publishDir = "hackerfarmindia.github.io"

[Author]
	name = "Rajanshu Ujjwal (Sunny)"

[params]
	description = "Radically Redefine Yourself"
	twitter = "hackerfarmindia"
	github = "hackerfarmindia"